// <auto-generated />
using DemoUniReg.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DemoUniReg.Api.Migrations
{
    [DbContext(typeof(RecordContext))]
    [Migration("20240523093026_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DemoUniReg.Api.Models.StudentDetail", b =>
                {
                    b.Property<int>("StudentMIS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentMIS"));

                    b.Property<string>("Course")
                        .HasColumnType("text");

                    b.Property<string>("Department")
                        .HasColumnType("text");

                    b.Property<string>("HallName")
                        .HasColumnType("text");

                    b.Property<string>("StudentName")
                        .HasColumnType("text");

                    b.HasKey("StudentMIS");

                    b.ToTable("StudentDetails", (string)null);
                });

            modelBuilder.Entity("DemoUniReg.Api.Models.StudentMIS", b =>
                {
                    b.Property<int>("SchoolID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SchoolID"));

                    b.Property<string>("Pin")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("SchoolID");

                    b.ToTable("StudentMISs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
